In [4]:
%matplotlib inline
%load_ext autoreload
%autoreload 2
import sys
import matplotlib.pyplot as plt
import numpy as np
import os
from pathlib import Path

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Load the experiment and corresponding libraries

In [7]:
project_path = os.path.join(Path.home(), "projects")
sys.path.append(project_path)  # enable import of "bias_transfer_recipes"
os.chdir(os.path.join(project_path,"bias_transfer_recipes/work/"))

In [13]:
from bias_transfer_recipes.bias_transfer_recipes.main import load_experiment
experiment = load_experiment(recipe="_2020_09_10_benchmark", 
                             experiment="test", 
                             schema="bias_transfer_test",  # schema name will automatically be generated from recipe and experiment names 
                             base_dir=os.path.join(project_path,"bias_transfer_recipes/bias_transfer_recipes/"),
                             import_prefix="bias_transfer_recipes.bias_transfer_recipes.", 
                             dev_mode=True  
                            )

In [14]:
from bias_transfer.tables.transfer import *
from bias_transfer.tables.nnfabrik import *
schema

Connecting anix@datajoint-db.mlcloud.uni-tuebingen.de:3306


Schema `bias_transfer_test`

### Run experiments

In [15]:
from bias_transfer_recipes.bias_transfer_recipes.main import fill_tables, run_all_experiments

In [17]:
fill_tables(experiment.transfer_experiments)  

In [18]:
run_all_experiments(experiment.transfer_experiments)

  0%|          | 0/2 [00:00<?, ?it/s]

Loading dataset: MNIST-IB
Model with 134954 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 26.51it/s, img_classification accuracy =74.8958, img_classification loss =0.6735, patience =0.0000]
Nothing to delete
Restoring best model from epoch! 1
Test Epoch 1: 100%|██████████| 79/79 [00:02<00:00, 28.01it/s, img_classification accuracy =74.3574, img_classification loss =0.6888]


 50%|█████     | 1/2 [00:47<00:47, 47.30s/it]

Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 511410 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 26.68it/s, img_classification accuracy =64.4941, img_classification loss =0.8863, patience =0.0000]
Nothing to delete
Restoring best model from epoch! 1
Test Epoch 1: 100%|██████████| 79/79 [00:02<00:00, 32.26it/s, img_classification accuracy =63.5864, img_classification loss =0.9027]


100%|██████████| 2/2 [01:24<00:00, 42.31s/it]

Deleting intermediate checkpoints...



  0%|          | 0/4 [00:00<?, ?it/s]

Loading dataset: MNIST-IB
Model with 511410 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 29.04it/s, img_classification accuracy =71.9953, img_classification loss =0.7277, patience =0.0000]
Nothing to delete
Restoring best model from epoch! 1
Test Epoch 1: 100%|██████████| 79/79 [00:02<00:00, 29.90it/s, img_classification accuracy =71.6072, img_classification loss =0.7434]


 25%|██▌       | 1/4 [00:26<01:18, 26.11s/it]

Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 134954 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 25.94it/s, img_classification accuracy =79.4299, img_classification loss =0.5330, patience =0.0000]
Nothing to delete
Restoring best model from epoch! 1
Test Epoch 1: 100%|██████████| 79/79 [00:02<00:00, 30.76it/s, img_classification accuracy =79.4279, img_classification loss =0.5390]


 50%|█████     | 2/4 [00:51<00:51, 25.93s/it]

Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 134954 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 26.14it/s, img_classification accuracy =76.6461, img_classification loss =0.6200, patience =0.0000]
Nothing to delete
Restoring best model from epoch! 1
Test Epoch 1: 100%|██████████| 79/79 [00:02<00:00, 31.04it/s, img_classification accuracy =75.8976, img_classification loss =0.6353]


 75%|███████▌  | 3/4 [01:14<00:25, 25.01s/it]

Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 511410 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 27.77it/s, img_classification accuracy =83.8306, img_classification loss =0.4636, patience =0.0000]
Nothing to delete
Restoring best model from epoch! 1
Test Epoch 1: 100%|██████████| 79/79 [00:02<00:00, 27.18it/s, img_classification accuracy =82.7183, img_classification loss =0.4876]


100%|██████████| 4/4 [01:38<00:00, 24.68s/it]

Deleting intermediate checkpoints...



  0%|          | 0/4 [00:00<?, ?it/s]

Loading dataset: MNIST-IB
Model with 511410 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 29.19it/s, img_classification accuracy =66.9445, img_classification loss =0.8573, patience =0.0000]
Restoring best model from epoch! 0
Test Epoch 0: 100%|██████████| 79/79 [00:02<00:00, 29.91it/s, img_classification accuracy =67.0067, img_classification loss =0.8726]


 25%|██▌       | 1/4 [00:06<00:20,  6.91s/it]

Nothing to delete
Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 134954 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 25.98it/s, img_classification accuracy =74.4457, img_classification loss =0.6566, patience =0.0000]
Restoring best model from epoch! 0
Test Epoch 0: 100%|██████████| 79/79 [00:02<00:00, 29.64it/s, img_classification accuracy =74.8675, img_classification loss =0.6653]


 50%|█████     | 2/4 [00:13<00:13,  6.89s/it]

Nothing to delete
Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 134954 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 28.74it/s, img_classification accuracy =74.3291, img_classification loss =0.6748, patience =0.0000]
Restoring best model from epoch! 0
Test Epoch 0: 100%|██████████| 79/79 [00:02<00:00, 26.87it/s, img_classification accuracy =74.1074, img_classification loss =0.6861]


 75%|███████▌  | 3/4 [00:20<00:06,  6.93s/it]

Nothing to delete
Deleting intermediate checkpoints...
Loading dataset: MNIST-IB
Model with 511410 parameters.
==> Starting model 
Validation Epoch 0: 100%|██████████| 47/47 [00:01<00:00, 28.13it/s, img_classification accuracy =52.3921, img_classification loss =1.3833, patience =0.0000]
Restoring best model from epoch! 0
Test Epoch 0: 100%|██████████| 79/79 [00:02<00:00, 27.44it/s, img_classification accuracy =52.0152, img_classification loss =1.4017]


100%|██████████| 4/4 [00:28<00:00,  7.02s/it]

Nothing to delete
Deleting intermediate checkpoints...


In [ ]:
%debug

In [10]:
from nnfabrik.templates.trained_model_chkpts import Checkpoint

In [11]:
Checkpoint()

*collapsed_key *model_fn    *model_hash    *dataset_fn    *dataset_hash  *trainer_fn    *trainer_hash  *seed    *epoch    score     state      fabrikant_name trainedmodel_t
+------------+ +----------+ +------------+ +------------+ +------------+ +------------+ +------------+ +------+ +-------+ +-------+ +--------+ +------------+ +------------+

 (Total: 0)

In [10]:
# dElete all jobs in error state:
if schema.database != "nnfabrik_core": 
    (schema.jobs & "status='error'").delete()

In [48]:
# drop the entire schema: THIS IS WILL DELETE EVERYTHING!
if schema.database != "nnfabrik_core": 
    schema.drop()

Proceed to delete entire schema `anix_nnfabrik_test`? [yes, No]:  yes


In [46]:
from torch.utils.tensorboard import SummaryWriter
import numpy as np
import torch

experiment = "noisy_test"
run = "next run"
state = torch.load(Checkpoint().fetch("state",as_dict=True)[0]["state"])
tracker = state["tracker"]


In [47]:
def write_to_tensor_board(experiment, run, tracker):
    writer = SummaryWriter()
    def write_objective(obj_names, obj):
        if isinstance(obj,dict):
            for obj_name, sub_obj in obj.items():
                if obj_name == "normalization":
                    continue
                write_objective(obj_names+[obj_name],sub_obj)
        else:
            obj_val = tracker.get_objective(*obj_names)
            for i, val in enumerate(obj_val):
                writer.add_scalar('/'.join([run]+obj_names), val, i)
            
    write_objective([],tracker.objectives)
write_to_tensor_board(experiment, run, tracker)

/src/ml-utils/mlutils/tracking.py:144: RuntimeWarning: invalid value encountered in true_divide
  n_log[key] = l / norm


In [33]:
tracker.objectives

{'LR': 0,
 'Training': {'img_classification': {'loss': 0,
   'accuracy': 0,
   'normalization': 0},
  'NoiseAdvTraining': {'loss': 0, 'normalization': 0}},
 'Validation': {'img_classification': {'loss': 0,
   'accuracy': 0,
   'normalization': 0},
  'NoiseAdvTraining': {'loss': 0, 'normalization': 0}},
 'Test': {'NoiseAdvTraining': {'loss': 0, 'normalization': 0}}}

In [42]:
tracker.log

{'LR': [0.0003, 0.0003, 0.0003, 0],
 'Training': {'img_classification': {'loss': [312.89678955078125,
    477.7629699707031,
    316.83843994140625,
    0],
   'accuracy': [1900, 1900, 1100, 0],
   'normalization': [128, 128, 128, 0]},
  'NoiseAdvTraining': {'loss': [3.6585111916065216,
    5.0233617424964905,
    1.6073499619960785,
    0],
   'normalization': [60, 60, 60, 0]}},
 'Validation': {'img_classification': {'loss': [297.705322265625,
    298.799072265625,
    294.47955322265625,
    292.99310302734375],
   'accuracy': [2500, 1200, 3400, 2800],
   'normalization': [128, 128, 128, 128]},
  'NoiseAdvTraining': {'loss': [1.491750106215477,
    1.491749994456768,
    1.491749882698059,
    1.491750106215477],
   'normalization': [60, 60, 60, 60]}},
 'Test': {'NoiseAdvTraining': {'loss': [0, 0, 0, 0],
   'normalization': [0, 0, 0, 0]}}}

In [36]:
tracker.get_objective("LR")
tracker.get_objective("Training","img_classification","accuracy")

array([14.84375, 14.84375,  8.59375,      nan])

In [5]:
import torch
import numpy as np

In [6]:
from torchvision.datasets import SVHN
from torchvision import transforms

In [7]:
transform = transforms.Compose([
        transforms.ToTensor(),
#         transforms.Normalize((0.1307,), (0.3081,))
        ])
train = SVHN(
            root="/work/",
            split="train",
            download=True,
            transform=transform,
        )

Using downloaded and verified file: /work/train_32x32.mat


In [8]:
train_set = torch.utils.data.DataLoader(
        train,
        batch_size=64,
        shuffle=False,
    )
next(iter(train_set))[0].shape

torch.Size([64, 3, 32, 32])

In [65]:
mean = 0.
std = 0.
nb_samples = 0.
data_ = []
for data, _ in train_set:
    data_.append(data)
    batch_samples = data.size(0)
    data = data.view(batch_samples, data.size(1), -1)
    mean += data.mean(2).sum(0)
    std += data.std(2).sum(0)
    nb_samples += batch_samples

mean /= nb_samples
std /= nb_samples
dataset = torch.cat(data_)

In [66]:
print(mean,std)

tensor([0.4377, 0.4438, 0.4728]) tensor([0.1201, 0.1231, 0.1052])


In [67]:
std_ = dataset.std([0, 2, 3])
mean_ = dataset.mean([0, 2, 3])

In [68]:
std_

tensor([0.1980, 0.2010, 0.1970])

In [69]:
mean_

tensor([0.4377, 0.4438, 0.4728])

In [70]:
dataset.shape

torch.Size([73257, 3, 32, 32])